version: "3.1"

services:

  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    ports:
      - "8080:8080"
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=example
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update


  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"